added load more feature to FAQs
GlobeHoppin/GlobeHoppin pull request #92
Opened 2024-10-16 13:19 UTC by AswaniBolisetti

@Mustafiz04 
I have added load more feature to FAQs, Kindly check it out

https://github.com/user-attachments/assets/dfd7e456-d7ae-4065-bc5f-c785dbf3c178

2024-10-16 15:00 UTC, AswaniBolisetti commented
@Mustafiz04 I have done the work as you said. If user click the 'Know More' button, then all the FAQs will be shown in the seperate page and i have added a button in all faqs page for redirecting to the home page again
Kindly check it out


https://github.com/user-attachments/assets/d72a96e7-97e9-48eb-a0cb-5ce847531b2b

2024-10-17 03:31 UTC, AswaniBolisetti commented
@Mustafiz04 
Could you please review and merge it

2024-10-17 05:32 UTC, Mustafiz04 requested changes

2024-10-17 05:32 UTC, Mustafiz04 commented on src/data/morefaq.json
> +    {
You can merge both faqData and moreFaq into into single fine. On home just display top 5.

2024-10-17 05:32 UTC, Mustafiz04 commented on src/pages/faq.jsx
> +        <h2 className="text-5xl font-bold text-white mb-8 text-center">All FAQs</h2>
I believe we already have FAQ component you can use that in both places.
One home page use prop to check how many faq to show by default show all.

2024-10-17 05:43 UTC, AswaniBolisetti commented
I tried to do it with the same data file and same component, but i couldn't do it,

2024-10-17 05:59 UTC, Mustafiz04 commented
> I tried to do it with the same data file and same component, but i couldn't do it, so i created a seperate route for faq which uses morefaq.json file to display all the faqs

You can, it require small logic. It will good learning for you.
We don't have to repeat the code.

Also rebase and resolve merge conflict.

2024-10-17 08:13 UTC, AswaniBolisetti commented
@Mustafiz04 
Thank you, I deleted the duplicate data file and created faq page using the same json file, now you can check it out, I resolved the conflicts too

2024-10-17 17:13 UTC, Mustafiz04 approved these changes

2024-10-17 17:14 UTC, Mustafiz04 commented
Resolve the merge conflict again, please.

2024-10-18 00:43 UTC, AswaniBolisetti commented
@Mustafiz04 resolved, check once

2024-10-18 06:49 UTC, AswaniBolisetti commented
> @Mustafiz04 resolved, check once

@Mustafiz04 could you please review and merge it

2024-10-21 15:41 UTC, Mustafiz04 approved these changes

2024-10-21 15:41 UTC, merged